### ISSUE TITLE
Python 3.3 socket exception

### ISSUE THREAD

**Issue by Komnomnomnom** [Komnomnomnom/swigibpy#26]
From @azyr in #25 

> Whenever an exception gets raised (from my erroneous code) it somehow gets caught and I only get  some useless output on EWrapper.Error. The output comes with code 509 and says: "Exception caught while reading socket - std::exception". This is very annoying because now I have no idea what I did wrong. Any ideas how can I raise the exceptions unhandled so I will know exactly what is going on?

**Comment by sandrinr** [comment]
This happens when Python code inside your swigibpy.EWrapper methods raises an exception. This is an awkward situation since it appears that SWIG assumes the underlying (the wrapped) library being able to cope with such exceptions, it does not seem to surround all calls with "try catch" clauses. For me this looks like a SWIG issue (but to be honest I have not much of an idea of SWIG).

I get around this by putting a "try ... catch" around all my code inside EWrapper methods.

**Comment by Komnomnomnom** [comment]
@sandrinr the problem is that the EWrapper code is called from swigibpy's poll thread, so any exception bubbles up and kills the thread and socket connection. 

It needs to be modified to either make the calls in another thread or deal with the generated exceptions, by printing them or preferably notifying user code that an exception occurred.

**Comment by sandrinr** [comment]
I dug into this a little bit more today. As far as I can see (in EClientSocketBase::processMsg), with the current version of the IB API all errors are already catched in the C++ layer and are printed through the C++ error method yielding in the common error message stated above in this thread. As long as the error handling code does not raise an exception itself it is impossible for the "TWSPoller" thread to be killed. Also catching any exception in the poller thread has no effect since they are not bubbled up to that point int the stack.

Therefore, I think an opportunistic approach would be to patch any Python EWrapper class (when it is submitted to the ESocketClient class) in such a way, that all method calls on the EWrapper are wrapped with a "try catch" in the Python context, which would print a nice Pythonic stack trace when an exception is catched?

Any other suggestions on how to address this issue?

**Comment by Komnomnomnom** [comment]
@sandrinr all wrapper calls are dispatched from the `checkMessages` call in the poll thread [here](https://github.com/Komnomnomnom/swigibpy/blob/master/swigify_ib.i#L143) so it would be enough to wrap this in a `try...catch` to capture all Python exceptions. 

I'd like the user's code to be notified that an exception has happened though (just printing to the terminal is rarely good enough). I'm going to experiment with augmenting the `EWrapper` with an additional `pyError` method.

**Comment by Komnomnomnom** [comment]
You are right about the exceptions being caught in `processMsg` but it might be possible to get SWIG to deal with exceptions in Python before it gets back C (without a `try...except` on every method call)

**Comment by Komnomnomnom** [comment]
I've introduced a new `EWrapper` method called `pyError` which will be called with the exception details if an exception occurs during invocation of one of the user defined `EWrapper` Python methods. By default it will just print the traceback to standard error but it can be overridden with your own custom handling. Please give it a try.

**Comment by sandrinr** [comment]
I just looked at the change and also tested it on my side. Seems to work as expected. I also like the extensibility. I for my part like to log these things through the Python logging framework which is easily possible with your solution. You've got some serious SWIG <-> Python knowledge going on there ;-).

I guess this issue can be marked as resolved.

**Comment by Komnomnomnom** [comment]
Excellent! Thanks for the feedback.
